#Large Crystal properties file
#Wed May 27 18:04:51 UTC 2026
shouldGenerateEchoCrystal=true
shouldGenerateGlowstoneCrystal=true
shouldGeneratePrismarineCrystal=true
shouldGenerateQuartzCrystal=true
shouldGenerateWrappistCrystal=true
