#Large Crystal properties file
#Thu May 28 06:54:32 UTC 2026
shouldGenerateEchoCrystal=true
shouldGenerateGlowstoneCrystal=true
shouldGeneratePrismarineCrystal=true
shouldGenerateQuartzCrystal=true
shouldGenerateWrappistCrystal=true
