#Nether Geodes properties file
#Thu May 28 06:54:32 UTC 2026
shouldGenerateNetherDebrisGeodes=false
shouldGenerateNetherGlowstoneGeodes=true
shouldGenerateNetherGoldNuggetGeodes=true
shouldGenerateNetherQuartzGeodes=true
