#Nether Geodes properties file
#Thu May 28 22:55:28 UTC 2026
shouldGenerateNetherDebrisGeodes=false
shouldGenerateNetherGlowstoneGeodes=true
shouldGenerateNetherGoldNuggetGeodes=true
shouldGenerateNetherQuartzGeodes=true
