#Nether Geodes properties file
#Sat Jun 06 16:49:45 UTC 2026
shouldGenerateNetherDebrisGeodes=false
shouldGenerateNetherGlowstoneGeodes=true
shouldGenerateNetherGoldNuggetGeodes=true
shouldGenerateNetherQuartzGeodes=true
