#Overworld Geodes properties file
#Thu May 28 06:54:32 UTC 2026
shouldGenerateCelestiteGeodes=true
shouldGenerateDiamondGeodes=true
shouldGenerateEchoGeodes=true
shouldGenerateEmeraldGeodes=true
shouldGenerateLapisGeodes=true
shouldGeneratePinkTopazGeodes=true
shouldGeneratePrismarineGeodes=true
shouldGenerateRedstoneGeodes=true
