#Overworld Geodes properties file
#Fri May 29 09:42:44 UTC 2026
shouldGenerateCelestiteGeodes=true
shouldGenerateDiamondGeodes=true
shouldGenerateEchoGeodes=true
shouldGenerateEmeraldGeodes=true
shouldGenerateLapisGeodes=true
shouldGeneratePinkTopazGeodes=true
shouldGeneratePrismarineGeodes=true
shouldGenerateRedstoneGeodes=true
