#Overworld Geodes properties file
#Wed May 27 17:11:34 UTC 2026
shouldGenerateCelestiteGeodes=true
shouldGenerateDiamondGeodes=true
shouldGenerateEchoGeodes=true
shouldGenerateEmeraldGeodes=true
shouldGenerateLapisGeodes=true
shouldGeneratePinkTopazGeodes=true
shouldGeneratePrismarineGeodes=true
shouldGenerateRedstoneGeodes=true
